title: "Backyard Barns"
description: "A platform for hobby horse enthusiasts"
#baseurl: "/" # the subpath of your site
url: "https://backyardbarns.org" # the base hostname & protocol for your site
theme: minima

# Defaults for Markdown files
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Backyard Barns"
      
markdown: kramdown
